type Props = {
  params: Promise<{ locale: string }>;
};

/**
 * Terms of Service Page - SSG
 * Displays the terms and conditions for using the service.
 */
export default async function TermsPage({ params }: Props) {
  await params;

  return (
    <div className="mx-auto max-w-4xl px-4 py-16 sm:px-6 lg:px-8">
      <article className="prose prose-slate dark:prose-invert max-w-none">
        <h1 className="scroll-m-20 text-4xl font-extrabold tracking-tight lg:text-5xl">
          Terms of Service – Local Responder
        </h1>

        <p className="leading-7 [&:not(:first-child)]:mt-6 text-muted-foreground">
          Operated by NUMA LABS LLC
        </p>

        <p className="leading-7 [&:not(:first-child)]:mt-6 text-muted-foreground">
          Last Updated: November 1, 2025
        </p>

        <h2 className="mt-10 scroll-m-20 border-b pb-2 text-3xl font-semibold tracking-tight transition-colors first:mt-0">
          1. Introduction
        </h2>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          These Terms of Service (&quot;Terms&quot;) govern your access and use of Local Responder, a platform operated by NUMA LABS LLC (&quot;NUMA LABS&quot;, &quot;we&quot;, &quot;us&quot;, or &quot;the Company&quot;). Local Responder enables businesses to connect their Google Business Profile, analyze reviews, and respond to customers using AI-generated content.
        </p>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          By creating an account, connecting your Google Business Profile, or using Local Responder, you agree to these Terms.
        </p>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          If you do not agree, you must stop using the service immediately.
        </p>

        <h2 className="mt-10 scroll-m-20 border-b pb-2 text-3xl font-semibold tracking-tight transition-colors">
          2. The Service
        </h2>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          Local Responder provides tools to:
        </p>

        <ul className="my-6 ml-6 list-disc [&>li]:mt-2">
          <li>Connect your Google Business Profile via OAuth</li>
          <li>Retrieve customer reviews</li>
          <li>Analyze and summarize review content</li>
          <li>Generate AI-powered responses</li>
          <li>Publish review responses on your behalf</li>
          <li>Manage multiple business locations</li>
          <li>Receive notifications via WhatsApp</li>
        </ul>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          You are fully responsible for reviewing and approving responses generated by the system.
        </p>

        <h2 className="mt-10 scroll-m-20 border-b pb-2 text-3xl font-semibold tracking-tight transition-colors">
          3. Eligibility
        </h2>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          To use Local Responder, you must:
        </p>

        <ul className="my-6 ml-6 list-disc [&>li]:mt-2">
          <li>Be at least 18 years old</li>
          <li>Have authority to act on behalf of the represented business</li>
          <li>Use the service for lawful business purposes</li>
          <li>Have a valid Google account and the necessary permissions for the location(s) connected</li>
        </ul>

        <h2 className="mt-10 scroll-m-20 border-b pb-2 text-3xl font-semibold tracking-tight transition-colors">
          4. Google OAuth and Required Permissions
        </h2>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          To operate, Local Responder requires the OAuth scope:
        </p>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          https://www.googleapis.com/auth/business.manage
        </p>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          This allows the platform to:
        </p>

        <ul className="my-6 ml-6 list-disc [&>li]:mt-2">
          <li>Access your Business Profile locations</li>
          <li>Retrieve existing and new reviews</li>
          <li>Publish responses in your name</li>
        </ul>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          We do not access or modify any other Google data.
        </p>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          You may revoke access at any time through your Google Account settings.
        </p>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          Revoking access may disable core features of the service.
        </p>

        <h2 className="mt-10 scroll-m-20 border-b pb-2 text-3xl font-semibold tracking-tight transition-colors">
          5. Account Registration
        </h2>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          To use Local Responder, you must create an account by logging in with Google.
        </p>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          You may additionally provide:
        </p>

        <ul className="my-6 ml-6 list-disc [&>li]:mt-2">
          <li>Phone number (for WhatsApp)</li>
          <li>Billing information of your organization</li>
        </ul>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          You must ensure that all information is accurate and kept up to date.
        </p>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          You are responsible for maintaining the confidentiality of your credentials and account activity.
        </p>

        <h2 className="mt-10 scroll-m-20 border-b pb-2 text-3xl font-semibold tracking-tight transition-colors">
          6. Subscription, Billing &amp; Free Trial
        </h2>

        <h3 className="mt-8 scroll-m-20 text-2xl font-semibold tracking-tight">
          6.1. Pricing
        </h3>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          Local Responder is billed at $20 USD per location per month.
        </p>

        <h3 className="mt-8 scroll-m-20 text-2xl font-semibold tracking-tight">
          6.2. Free Trial
        </h3>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          Each new account includes a 15-day free trial with full functionality.
        </p>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          No charges are made during the trial.
        </p>

        <h3 className="mt-8 scroll-m-20 text-2xl font-semibold tracking-tight">
          6.3. Billing via Stripe
        </h3>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          Stripe acts as our payment processor, handling:
        </p>

        <ul className="my-6 ml-6 list-disc [&>li]:mt-2">
          <li>Payments</li>
          <li>Invoices</li>
          <li>Taxes</li>
          <li>Compliance</li>
        </ul>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          We do not store credit card details.
        </p>

        <h3 className="mt-8 scroll-m-20 text-2xl font-semibold tracking-tight">
          6.4. Upgrades &amp; Downgrades
        </h3>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          You may add or remove locations at any time.
        </p>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          Billing adjustments are handled automatically by Stripe.
        </p>

        <h3 className="mt-8 scroll-m-20 text-2xl font-semibold tracking-tight">
          6.5. Cancellation
        </h3>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          You may cancel your subscription at any time.
        </p>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          Access will remain active until the end of the billing period.
        </p>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          No refunds are provided for partial billing cycles unless required by law.
        </p>

        <h2 id="refund-policy" className="mt-10 scroll-m-20 border-b pb-2 text-3xl font-semibold tracking-tight transition-colors">
          7. Refund Policy
        </h2>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          Local Responder is a subscription-based SaaS product with a 15-day free trial that allows users to fully test all features before any charges are applied. Because the trial provides complete access without limitations, we generally do not offer refunds once a paid subscription period has started.
        </p>

        <h3 className="mt-8 scroll-m-20 text-2xl font-semibold tracking-tight">
          7.1. Free Trial
        </h3>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          All new accounts include a 15-day free trial with full functionality.
        </p>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          No charges are made until the trial ends.
        </p>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          You may cancel at any time during the trial to avoid being billed.
        </p>

        <h3 className="mt-8 scroll-m-20 text-2xl font-semibold tracking-tight">
          7.2. Monthly Subscriptions
        </h3>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          Monthly subscriptions are billed in advance and are non-refundable, except where required by applicable consumer law.
        </p>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          This includes:
        </p>

        <ul className="my-6 ml-6 list-disc [&>li]:mt-2">
          <li>Unused time in the current billing cycle</li>
          <li>Downgrades after the billing date</li>
          <li>Lack of use of the service</li>
        </ul>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          Your subscription will remain active until the end of the paid period.
        </p>

        <h3 className="mt-8 scroll-m-20 text-2xl font-semibold tracking-tight">
          7.3. Charges per Location
        </h3>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          Subscription fees are charged per active location connected to Local Responder.
        </p>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          If you remove a location, the change will take effect starting on the next billing cycle.
        </p>

        <h3 className="mt-8 scroll-m-20 text-2xl font-semibold tracking-tight">
          7.4. Cancellations
        </h3>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          You may cancel your subscription at any time through your account dashboard.
        </p>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          Cancellation prevents future charges but does not generate a refund for past payments.
        </p>

        <h3 className="mt-8 scroll-m-20 text-2xl font-semibold tracking-tight">
          7.5. Billing Disputes
        </h3>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          If you believe you were billed incorrectly, you must contact us within 14 days of the charge.
        </p>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          We will review the request and determine eligibility for an exceptional refund based on:
        </p>

        <ul className="my-6 ml-6 list-disc [&>li]:mt-2">
          <li>Duplicate charges</li>
          <li>Technical issues preventing service use</li>
          <li>Situations mandated by consumer protection laws</li>
        </ul>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          Refund decisions remain at the sole discretion of NUMA LABS LLC.
        </p>

        <h3 className="mt-8 scroll-m-20 text-2xl font-semibold tracking-tight">
          7.6. Stripe as Payment Processor
        </h3>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          All transactions are processed by Stripe, our payment processor.
        </p>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          Refunds, where applicable, may be handled directly by Stripe following their own compliance procedures.
        </p>

        <h3 className="mt-8 scroll-m-20 text-2xl font-semibold tracking-tight">
          7.7. No Refunds for API Changes or Third-Party Outages
        </h3>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          Because Local Responder depends on third-party services (Google Business Profile, WhatsApp, Stripe), outages or changes in those services do not qualify for refunds.
        </p>

        <h2 className="mt-10 scroll-m-20 border-b pb-2 text-3xl font-semibold tracking-tight transition-colors">
          8. Acceptable Use
        </h2>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          You agree not to:
        </p>

        <ul className="my-6 ml-6 list-disc [&>li]:mt-2">
          <li>Use Local Responder for fraudulent, illegal, or harmful purposes</li>
          <li>Violate Google Business Profile policies when responding to reviews</li>
          <li>Misuse AI-generated content to harass, deceive, or manipulate customers</li>
          <li>Interfere with the platform&apos;s operation</li>
          <li>Attempt to access other users&apos; accounts or data</li>
        </ul>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          We may suspend or terminate accounts that violate these rules.
        </p>

        <h2 className="mt-10 scroll-m-20 border-b pb-2 text-3xl font-semibold tracking-tight transition-colors">
          9. AI-Generated Content
        </h2>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          Local Responder uses artificial intelligence to generate review summaries and responses. You acknowledge that:
        </p>

        <ul className="my-6 ml-6 list-disc [&>li]:mt-2">
          <li>AI content is generated automatically</li>
          <li>You are responsible for reviewing information before publication</li>
          <li>We are not liable for inaccuracies, tone, or unintended interpretations</li>
        </ul>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          You maintain full editorial control and responsibility for all posted content.
        </p>

        <h2 className="mt-10 scroll-m-20 border-b pb-2 text-3xl font-semibold tracking-tight transition-colors">
          10. Availability and Service Modifications
        </h2>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          We strive to keep the platform available and reliable, but we do not guarantee:
        </p>

        <ul className="my-6 ml-6 list-disc [&>li]:mt-2">
          <li>Uninterrupted operation</li>
          <li>Error-free performance</li>
          <li>Compatibility with all devices or browsers</li>
        </ul>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          We may update, modify, or discontinue parts of the service at any time.
        </p>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          Where possible, we will provide reasonable notice.
        </p>

        <h2 className="mt-10 scroll-m-20 border-b pb-2 text-3xl font-semibold tracking-tight transition-colors">
          11. Data Protection
        </h2>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          Your use of the service is governed by our Privacy Policy, which explains:
        </p>

        <ul className="my-6 ml-6 list-disc [&>li]:mt-2">
          <li>What data we collect</li>
          <li>How we use it</li>
          <li>Your rights regarding personal data</li>
        </ul>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          By using Local Responder, you agree to the Privacy Policy.
        </p>

        <h2 className="mt-10 scroll-m-20 border-b pb-2 text-3xl font-semibold tracking-tight transition-colors">
          12. Intellectual Property
        </h2>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          All content, code, design, and trademarks of Local Responder belong to NUMA LABS LLC.
        </p>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          You may not:
        </p>

        <ul className="my-6 ml-6 list-disc [&>li]:mt-2">
          <li>Copy</li>
          <li>Modify</li>
          <li>Reverse engineer</li>
          <li>Redistribute</li>
        </ul>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          any aspect of the platform without written permission.
        </p>

        <h2 className="mt-10 scroll-m-20 border-b pb-2 text-3xl font-semibold tracking-tight transition-colors">
          13. Termination
        </h2>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          We may suspend or terminate your account if:
        </p>

        <ul className="my-6 ml-6 list-disc [&>li]:mt-2">
          <li>You violate these Terms</li>
          <li>You misuse the service</li>
          <li>You fail to pay subscription fees</li>
        </ul>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          You may terminate your account at any time by contacting support or via the dashboard.
        </p>

        <h2 className="mt-10 scroll-m-20 border-b pb-2 text-3xl font-semibold tracking-tight transition-colors">
          14. Limitation of Liability
        </h2>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          To the maximum extent permitted by law:
        </p>

        <ul className="my-6 ml-6 list-disc [&>li]:mt-2">
          <li>Local Responder is provided &quot;as is&quot; and &quot;as available&quot;</li>
          <li>NUMA LABS LLC is not responsible for damages arising from:
            <ul className="my-2 ml-6 list-disc [&>li]:mt-2">
              <li>Service interruptions</li>
              <li>AI-generated content</li>
              <li>Loss of business or revenue</li>
              <li>Google API outages</li>
              <li>Unauthorized access due to your actions</li>
            </ul>
          </li>
          <li>Total liability shall not exceed the amount paid in the last 12 months</li>
        </ul>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          Some jurisdictions may provide additional rights.
        </p>

        <h2 className="mt-10 scroll-m-20 border-b pb-2 text-3xl font-semibold tracking-tight transition-colors">
          15. Third-Party Services
        </h2>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          Local Responder integrates with:
        </p>

        <ul className="my-6 ml-6 list-disc [&>li]:mt-2">
          <li>Google APIs</li>
          <li>WhatsApp</li>
          <li>Stripe (billing)</li>
          <li>Analytics providers</li>
        </ul>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          We are not responsible for the availability or operation of these third-party services.
        </p>

        <h2 className="mt-10 scroll-m-20 border-b pb-2 text-3xl font-semibold tracking-tight transition-colors">
          16. Governing Law &amp; Jurisdiction
        </h2>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          These Terms are governed by the laws of the State of Wyoming, United States.
        </p>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          Any legal disputes must be brought before the courts located in Wyoming, unless local consumer laws require otherwise.
        </p>

        <h2 className="mt-10 scroll-m-20 border-b pb-2 text-3xl font-semibold tracking-tight transition-colors">
          17. Modifications to the Terms
        </h2>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          We may update these Terms. The newest version will always be available on our website.
        </p>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          Continued use of the service after changes constitutes acceptance.
        </p>

        <h2 className="mt-10 scroll-m-20 border-b pb-2 text-3xl font-semibold tracking-tight transition-colors">
          18. Contact
        </h2>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          For questions regarding these Terms, please contact:
        </p>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          <strong>NUMA LABS LLC</strong>
        </p>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          407 Lincoln Road #708, Miami Beach, FL 33139, USA
        </p>

        <p className="leading-7 [&:not(:first-child)]:mt-6">
          Email: talk@numa-labs.com
        </p>
      </article>
    </div>
  );
}

